baseURL = "https://startupandrew.com/"
languageCode = "en-us"
title = "Andrew's Blog"
theme = "hyde-hyde"

## Site Settings
[params]
    author = "Andrew Lee"
    description = '''
Cofounder of Firebase, angel investor, and gymnast.
I care about Haiti, digital freedoms, and empowering individuals.
'''
    authorimage = "/images/andrew.jpg"
    dateformat = "Jan 2, 2006"
    highlightjs = true
    highlightjsstyle = "github"
    themeColor = "theme-base-0c"
    GoogleAnalyticsID = "UA-124285775-1"
    # please choose either GraphComment or Disqus

## Social Accounts
[params.social]
    github = "startupandrew"
    linkedin = "startupandrew"
    twitter = "startupandrew"

## Main Menu
##[[menu.main]]
##    name = "Posts"
##    weight = 100
##    identifier = "posts"
##    url = "/posts/"
[[menu.main]]
    name = "About Me"
    identifier = "about"
    weight = 300
    url = "/about/"
